name: 3D posters
favicon: null
layout_spectrum: 0.54305
typography_spectrum: 0.3777652243152261
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#ffffff'
    - '#525252'
    - '#aeaeae'
    - '#d14e00'
  brandStrength: 0.09940860350616276
  lightness: 0.375
  saturation: 0.697780376765877
  rhythmicContrast: 0.43741254159249365
purpose: []
