name: 3D posters
favicon: null
layout_spectrum: 0.99706
typography_spectrum: 0.33171
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010006'
    - '#a0b404'
    - '#013f7a'
    - '#009ffe'
    - '#fffefa'
  brandStrength: 0.09940860350616276
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
