name: 3D posters
favicon: null
layout_spectrum: 0.99119
typography_spectrum: 0.10959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00fefe'
    - '#010101'
    - '#039ed4'
    - '#68523b'
    - '#ffbb8a'
  brandStrength: 0.09940860350616276
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
