name: 3D posters
favicon: null
layout_spectrum: 0.99119
typography_spectrum: 0.33953
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#80cccc'
    - '#009999'
    - '#ff5050'
    - '#283f3f'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
